def generate_report(
    total_rows,
    quality_score,
    duplicate_count,
    label_count,
    semantic_count,
    mismatch_count
):

    if quality_score >= 90:
        status = "Excellent"
        risk = "Low"
    elif quality_score >= 75:
        status = "Good"
        risk = "Low"
    elif quality_score >= 50:
        status = "Moderate"
        risk = "Medium"
    else:
        status = "Poor"
        risk = "High"

    estimated_clean_records = (
        total_rows - duplicate_count
    )

    report = f"""
SMART LABEL QUALITY AUDIT REPORT
==================================================

EXECUTIVE SUMMARY
--------------------------------------------------
Dataset Quality Score : {quality_score}%
Dataset Status        : {status}
Risk Level            : {risk}
Total Records         : {total_rows}

ISSUE BREAKDOWN
--------------------------------------------------
Duplicate Records     : {duplicate_count}
Label Inconsistencies : {label_count}
Semantic Duplicates   : {semantic_count}
Possible Mislabels    : {mismatch_count}

TOP ISSUES DETECTED
--------------------------------------------------
• Duplicate records may introduce training bias.

• Inconsistent labels can reduce model accuracy.

• Semantic duplicates indicate repetitive data.

• Potential mislabels require manual review.

DATA QUALITY ASSESSMENT
--------------------------------------------------
The dataset was evaluated using duplicate
detection, label consistency checks,
semantic similarity analysis and anomaly
identification techniques.

RECOMMENDATIONS
--------------------------------------------------
✓ Remove duplicate entries

✓ Standardize label formatting

✓ Review semantic duplicates

✓ Correct mislabeled samples

✓ Re-run quality validation

ESTIMATED CLEAN DATASET
--------------------------------------------------
Expected Usable Records : {estimated_clean_records}

FINAL VERDICT
--------------------------------------------------
Dataset Quality Rating : {status}
Risk Assessment        : {risk}

Generated By:
Smart Label Quality Checker
==================================================
"""
    return report